#!/usr/bin/env bash
# scripts/roadmap.sh
#
# Regenerate ROADMAP.md from the open GitHub issues on
# ghostlobster/memorize-everything. Bash (not tsx like
# scripts/smoke-deck.ts) because this script only needs curl + jq,
# and the CI freshness check should not pay the pnpm install tax.
#
# Usage:
#   scripts/roadmap.sh                    # write ROADMAP.md
#   scripts/roadmap.sh --check            # exit 1 if committed file is stale
#   scripts/roadmap.sh --stdout           # print to stdout
#   scripts/roadmap.sh --from-json FILE   # render from a pre-fetched issues
#                                         # JSON file (skips the API call);
#                                         # mainly for tests and offline
#                                         # bootstrap when unauthenticated.
#
# Env:
#   GITHUB_TOKEN   optional; lifts the rate limit to 5000 req/hr.
#                  Without it, anonymous limit is 60 req/hr which is
#                  plenty for local + CI usage.

set -euo pipefail
export LC_ALL=C

OWNER="ghostlobster"
REPO="memorize-everything"
OUT_PATH="ROADMAP.md"

mode="write"
json_source=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)     mode="check";  shift ;;
    --stdout)    mode="stdout"; shift ;;
    --from-json)
      shift
      if [[ $# -eq 0 ]]; then
        echo "--from-json requires a path argument" >&2
        exit 2
      fi
      json_source="$1"
      shift
      ;;
    -h|--help)
      sed -n '3,22p' "$0"
      exit 0
      ;;
    *)
      echo "unknown flag: $1" >&2
      exit 2
      ;;
  esac
done

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$repo_root"

# ----------------------------------------------------------------------------
# Acquire issues JSON — either from disk (--from-json) or the live API
# (paginating via Link: rel="next").
# ----------------------------------------------------------------------------

all_issues="$(mktemp)"
trap 'rm -f "$all_issues"' EXIT

if [[ -n "$json_source" ]]; then
  if [[ ! -f "$json_source" ]]; then
    echo "--from-json: file not found: $json_source" >&2
    exit 1
  fi
  # Validate that it parses as a JSON array.
  if ! jq -e 'type == "array"' "$json_source" >/dev/null 2>&1; then
    echo "--from-json: $json_source is not a JSON array" >&2
    exit 1
  fi
  cp "$json_source" "$all_issues"
else
  echo "[]" > "$all_issues"

  auth_header=()
  if [[ -n "${GITHUB_TOKEN:-}" ]]; then
    auth_header=(-H "Authorization: Bearer ${GITHUB_TOKEN}")
  fi

  url="https://api.github.com/repos/${OWNER}/${REPO}/issues?state=open&per_page=100"

  while [[ -n "$url" ]]; do
    headers_file="$(mktemp)"
    body_file="$(mktemp)"
    http_status="$(curl -sS -o "$body_file" -D "$headers_file" -w "%{http_code}" \
      -H "Accept: application/vnd.github+json" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      "${auth_header[@]}" \
      "$url")"

    if [[ "$http_status" != "200" ]]; then
      echo "GitHub API returned HTTP $http_status for $url" >&2
      echo "--- response body ---" >&2
      cat "$body_file" >&2
      rm -f "$headers_file" "$body_file"
      exit 1
    fi

    # Merge this page into all_issues.
    jq -s '.[0] + .[1]' "$all_issues" "$body_file" > "$all_issues.tmp"
    mv "$all_issues.tmp" "$all_issues"

    # Extract the next page URL from the Link header if present.
    next_url="$(tr -d '\r' < "$headers_file" \
      | awk 'tolower($1) == "link:" { $1=""; print }' \
      | grep -oE '<[^>]+>;[[:space:]]*rel="next"' \
      | head -1 \
      | sed -E 's/^<([^>]+)>;.*/\1/' || true)"

    rm -f "$headers_file" "$body_file"
    url="${next_url:-}"
  done
fi

# ----------------------------------------------------------------------------
# Render markdown.
# ----------------------------------------------------------------------------

# Banner kept stable (no timestamps, no commit SHAs) so the file is
# byte-deterministic for a given issue state.
rendered="$(mktemp)"
trap 'rm -f "$all_issues" "$rendered"' EXIT

{
  cat <<'BANNER'
# Roadmap

Auto-generated by `scripts/roadmap.sh` from the open issues on
[`ghostlobster/memorize-everything`](https://github.com/ghostlobster/memorize-everything/issues).

**Do not hand-edit this file.** The `CI / Roadmap freshness` check
will fail, and the daily `roadmap-refresh` workflow will overwrite
your changes. To update locally:

```bash
./scripts/roadmap.sh
```

Source of truth: GitHub Issues. File ordering: ascending by issue
number.

## Open issues
BANNER

  open_count="$(jq '[.[] | select(.pull_request == null and .state == "open")] | length' "$all_issues")"

  if [[ "$open_count" == "0" ]]; then
    echo ""
    echo "_No open issues. Nothing pending._"
  else
    echo ""
    jq -r '
      def esc_md: gsub("\\|"; "\\|") | gsub("`"; "\\`");
      def first_body_line:
        (.body // "")
        | split("\n")
        | map(select(length > 0 and (test("^\\s*$") | not)))
        | (first // "");
      def truncate(n):
        if length > n then (.[0:n-1] + "…") else . end;

      [ .[] | select(.pull_request == null and .state == "open") ]
        | sort_by(.number)
        | .[]
        | (
            "- **[#\(.number)](\(.html_url))**"
            + (if (.labels | length) > 0
                then " " + (.labels | map("`" + .name + "`") | join(" "))
                else "" end)
            + " — \(.title | esc_md)"
            + (
                first_body_line
                | esc_md
                | gsub("\\s+"; " ")
                | sub("^\\s+"; "")
                | sub("\\s+$"; "")
                | if length > 0 then "\n  - " + truncate(120) else "" end
              )
          )
    ' "$all_issues"
  fi
} > "$rendered"

# ----------------------------------------------------------------------------
# Dispatch per mode.
# ----------------------------------------------------------------------------

case "$mode" in
  stdout)
    cat "$rendered"
    ;;
  write)
    mv "$rendered" "$OUT_PATH"
    # Prevent EXIT trap from rm -f'ing the mv'd file.
    trap 'rm -f "$all_issues"' EXIT
    echo "wrote $OUT_PATH ($open_count open issue(s))"
    ;;
  check)
    if [[ ! -f "$OUT_PATH" ]]; then
      echo "❌ $OUT_PATH is missing. Run: ./scripts/roadmap.sh" >&2
      exit 1
    fi
    if ! diff --unified=3 --label "committed/$OUT_PATH" --label "regenerated" "$OUT_PATH" "$rendered"; then
      echo "" >&2
      echo "❌ $OUT_PATH is stale or hand-edited." >&2
      echo "   Run: ./scripts/roadmap.sh" >&2
      exit 1
    fi
    echo "✅ $OUT_PATH is in sync with live issues ($open_count open)"
    ;;
esac
